name: Auto create/update README.md

on:
  # this is code for the eventual scheduled run
  
  #schedule:
  ## intro to scheduled actions: https://jasonet.co/posts/scheduled-actions/
  ## this runs at the end of every day
    #- cron: 0 0 * * *
  
  # this is for manual triggering of the workflow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Trigger this workflow to update the README.md'
        required: true
        default: 'Running this action will overwrite the current README.md'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
    
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install dependencies
        run: python -m pip install --upgrade pip setuptools

      
      - name: install python requirements
        run: pip install -r requirements.txt

      #create README.md
      - name: create markdown
        run: python create_registry.py ${{ secrets.GITHUB_TOKEN }} 

      - run: git config user.email "huaning.y@gmail.com"
      
      - run: git config user.name "huaning-yang"

      - name: check git status
        run: git status
      
      - name: stage changed files
        run: git add .

      - name: commit staged files
        run: git commit -m'auto update README.md'
      
      - name: fetch from master
        run: git fetch 
      
      - name: push
        run: git push 
